GET
http://127.0.0.1:8000/api/system/v1/mempool
@Content-Type: application/json

%%%

# Duration: 205 ms
# URL: http://127.0.0.1:8000/api/system/v1/mempool

# HTTP/1.1 200 OK

@Content-Length: 15
@Content-Type: application/json
@Date: Mon, 31 Jul 2017 12:12:45 GMT

{
  "size": 0
}