GET
http://127.0.0.1:8000/api/system/v1/mempool
@Content-Type: application/json

%%%

# Duration: 35 ms
# URL: http://127.0.0.1:8000/api/system/v1/mempool

# HTTP/1.1 200 OK

@Content-Length: 15
@Content-Type: application/json
@Date: Sat, 05 Aug 2017 20:42:23 GMT

{
  "size": 0
}