POST
http://127.0.0.1:8000/api/services/cryptocurrency/v1/wallets/transaction
@Content-Type: application/json

{
    "body": {
        "from": "03e657ae71e51be60a45b4bd20bcf79ff52f0c037ae6da0540a0e0066132b472",
        "to": "d1e877472a4585d515b13f52ae7bfded1ccea511816d7772cb17e1ab20830819",
        "amount": "10",
        "seed": "12623766328194547469"
    },
    "network_id": 0,
    "protocol_version": 0,
    "service_id": 1,
    "message_id": 2,
    "signature": "2c5e9eee1b526299770b3677ffd0d727f693ee181540e1914f5a84801dfd410967fce4c22eda621701c2b9c676ed62bc48df9c973462a8514ffb32bec202f103"
}
%%%

# Duration: 56 ms
# URL: http://127.0.0.1:8000/api/services/cryptocurrency/v1/wallets/transaction

# HTTP/1.1 409 Conflict

@Content-Length: 283
@Content-Type: text/plain
@Date: Mon, 31 Jul 2017 12:20:54 GMT

{
  "debug": "IncorrectRequest(BodyError { detail: \"Can\\'t parse body to the struct\", cause: JsonError(ErrorImpl { code: Message(\"data did not match any variant of untagged enum TransactionRequest\"), line: 0, column: 0 }) })",
  "description": "Can't parse body to the struct"
}